### ISSUE TITLE
通过docker方式无法部署成功，每隔30s容器就自动重启了

### ISSUE THREAD

**Issue by Li1Fan** [bboysoulcn/telemonitor#5]
主机环境为：ubuntu20.04
只修改了token跟id。

**Comment by bboysoulcn** [comment]
> 主机环境为：ubuntu20.04 只修改了token跟id。

看下日志

`docker logs -f telemonitor`

**Comment by Li1Fan** [comment]
```
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/telegram/request/_httpxrequest.py", line 276, in do_request
    res = await self._client.request(
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/main.py", line 141, in <module>
    main()
  File "/app/main.py", line 137, in main
    application.run_polling(allowed_updates=Update.ALL_TYPES)
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/telegram/ext/_application.py", line 836, in run_polling
    return self.__run(
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/telegram/ext/_application.py", line 1036, in __run
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/telegram/ext/_application.py", line 1025, in __run
    loop.run_until_complete(self.initialize())
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/telegram/ext/_application.py", line 495, in initialize
    await self.bot.initialize()
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 293, in initialize
    await super().initialize()
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/telegram/_bot.py", line 767, in initialize
    await self.get_me()
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 1873, in get_me
    return await super().get_me(
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/telegram/_bot.py", line 541, in decorator
    result = await func(self, *args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/telegram/_bot.py", line 902, in get_me
    result = await self._post(
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/telegram/_bot.py", line 629, in _post
    return await self._do_post(
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 347, in _do_post
    return await super()._do_post(
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/telegram/_bot.py", line 657, in _do_post
    return await request.post(
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 340, in _request_wrapper
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 330, in _request_wrapper
    code, payload = await self.do_request(
  File "/root/.cache/pypoetry/virtualenvs/serverstatus-9TtSrW0h-py3.10/lib/python3.10/site-packages/telegram/request/_httpxrequest.py", line 293, in do_request
    raise TimedOut from err
telegram.error.TimedOut: Timed out
```

**Comment by Li1Fan** [comment]
网络代理的问题
      - HTTP_PROXY=http://127.0.0.1:7890
      - HTTPS_PROXY=http://127.0.0.1:7890

**Comment by bboysoulcn** [comment]
> 网络代理的问题 - HTTP_PROXY=http://127.0.0.1:7890 - HTTPS_PROXY=http://127.0.0.1:7890

对的可以加个配置，同时可以看看

`https://github.com/bboysoulcn/teleproxy`

**Comment by Li1Fan** [comment]
感谢感谢！
还有一个问题，想知道是怎么实现的main.py程序启动失败就重启容器的？

**Comment by bboysoulcn** [comment]
> 感谢感谢！ 还有一个问题，想知道是怎么实现的main.py程序启动失败就重启容器的？

docker-compose.yaml
里面有一个 restart always 看下就知道了

**Comment by Li1Fan** [comment]
不是，我没理解的是，main.py执行失败怎么会导致容器停止运行。

**Comment by bboysoulcn** [comment]
> 不是，我没理解的是，main.py执行失败怎么会导致容器停止运行。

当你启动一个容器时，Docker会启动一个主进程。这个主进程是容器的入口点，也是容器生命周期的控制器。如果这个进程死掉，Docker就认为容器已经完成了它的工作，于是停止容器

**Comment by Li1Fan** [comment]
原来如此，受教受教，感谢解答！
